apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.rolling.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.rolling.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: rolling
spec:
  replicas: {{ .Values.rolling.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.rolling.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.rolling.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: rolling
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.rolling.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}{{ .Values.rolling.image.repository }}:{{ .Values.rolling.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.rolling.service.targetPort }}
              protocol: TCP
          env:
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.rolling.env.OTEL_SERVICE_NAME | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://{{ .Release.Name }}-otelcol:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: {{ .Values.global.otel.protocol | quote }}
            - name: OTEL_SEMCONV_STABILITY_OPT_IN
              value: {{ .Values.global.otel.semconvStabilityOptIn | quote }}
            {{- if .Values.global.useExponentialHistograms }}
            - name: USE_EXPONENTIAL_HISTOGRAMS
              value: "1"
            {{- end }}
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment={{ .Values.global.resourceAttributes.deploymentEnvironment }},host.name={{ .Values.global.resourceAttributes.hostName }},service.version={{ .Values.global.resourceAttributes.serviceVersion }}"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.rolling.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}