apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTnY3Q2NlcS8zNUl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeU1qUXlNREUyTXpWYUZ3MHpOVEV5TWpJeU1ESXhNelZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURrQ21Ibk9OWU5JUFFVKy94WlY0Y3hZRXJOOGJYYk8ybnJJT1dXcXNjZXRMSEhZL0NMSmZPb2ROSmIKZjE0VWl3eUNnVDZudkFBbmc1NE1Nckk2Ti9MRDJ2TG5UT2VMVWJJTEZUU2Z1WXR1ekxsZ0xFNERYc1RPZmJCTQpLdDkreG1GRlduczZhU0MzRFRiZWRyWkpqd0FvaVUyVHAxOTZkTWlGbWdSSHc1VnF0Qndoalh2MUxPalVScTBDCmhJdnphYktxMUZyYkRLWHZnc1JkekV1QXJObmpYSER6UVBnSTZYSkx1WXYwL0NlNUVGOGl3T1p2L3FrLzMvNDkKTVBJb2E3ME1vL3FtMENUTEM0KzhyVVIzelh0VHJIL0xvemNncVlJWkczeVcyVFhYakx6RDBDUTF1eEZWWUV0ZApmMGZrMDkrNXBwc0hQdjNYYldHSFFqMWtZamNQQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTeVhJQ0ROVHUwdURUNndxMWlQSkNRMWRRcUpUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjlDSzl2UDFLeQpRZXZJVWdFZVo3NVRWWWJGWDVvMDQ0NVQ5YWNFcEJrdFJYZ0ozUG5HZGNMcjBOcThOU2h6U054cXBoRnVpWGx0CmdqbjZwbERiVEQyMi9kZnlBNWV0aGpyZ1dhSUc3enpJK0pWcTVuT2tKVi9tYVZCSTBHZlk5Qzd4TFgyQ2U5QWIKc2dja2ZZMWJXS1h5Z1JkSGIvc2E2Und3Q2NWUzdMWUIrMW03MXlMVXVMcjhTODI0dk5iVmdFbVQrMWRNMkVJVwpLb1doNkNOWEVDNTg3cnZlUEw2TGFpWVpKZ1VWWE02QkVNdk1QZHBTdE5MTGxYeFJGSnl5V29kU2pIUmtYYlk4CmJQRU9ZS1daT1BIT3U4eHdaKzNUNTFxVjNhdW4wTTBtNE9hM2VzMDRnRytDY1FIZE03SkthUTRWTUx1Slp1YnIKRXZFQmYrWkxaVFQxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://01B0C9A827E3ADCAC0C03B9C9FEA5FA3.gr7.us-east-1.eks.amazonaws.com
  name: otel-demo
contexts:
- context:
    cluster: otel-demo
    user: otel-demo
  name: otel-demo
current-context: otel-demo
kind: Config
preferences: {}
users:
- name: otel-demo
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - otel-demo
      - --output
      - json
      - --role
      - arn:aws:iam::217139788599:role/otel-demo-eks-admin
      env:
      - name: AWS_PROFILE
        value: sso-dev-opentelemetry-account-admin
      interactiveMode: IfAvailable
      provideClusterInfo: false
